---
- name: Check installed Python packages
  hosts: localhost
  tasks:
    - name: List installed packages
      command: /usr/bin/python3 -m pip list
      register: pip_list

    - debug:
        var: pip_list.stdout_lines
