pipeline:
  identifier: Build_talbow_wf_1724944600297
  name: Build wf
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1724944546579
        repoName: talbow/wf
  stages:
    - stage:
        name: wf
        identifier: wf
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: wf_info_1
                  identifier: wf_info_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: ansible-playbook -i inventory/inventory.yml pf_info.yml
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
